package group.skills;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.widget.TextView;

import group.skills.list.cantrip.Acid_Splash;
import group.skills.list.cantrip.Create_Bonfire;
import group.skills.list.cantrip.Infestation;
import group.skills.list.cantrip.Mage_Hand;
import group.skills.list.level1.Fog_Cloud;
import group.skills.list.level1.Grease;
import group.skills.list.level1.Healing_Elixir;
import group.skills.list.level1.Ice_Knife;
import group.skills.list.level2.Air_Bubble;
import group.skills.list.level2.Cloud_of_Daggers;
import group.skills.list.level2.Dust_Devil;
import group.skills.list.level2.Flaming_Sphere;
import group.skills.list.level3.Conjure_Lesser_Demon;
import group.skills.list.level3.Sleet_Storm;
import group.skills.list.level3.Stinking_Cloud;
import group.skills.list.level3.Thunder_Step;
import group.skills.list.level4.Conjure_Minor_Elementals;
import group.skills.list.level4.Dimension_Door;
import group.skills.list.level4.Evards_Black_Tentacles;
import group.skills.list.level4.Galders_Speedy_Courier;
import group.skills.list.level5.Conjure_Elemental;
import group.skills.list.level5.Infernal_Calling;
import group.skills.list.level5.Steel_Wind_Strike;
import group.skills.list.level5.Teleportation_Circle;
import group.skills.list.level6.Arcane_Gate;
import group.skills.list.level6.Scatter_Conjuration;
import group.skills.list.level7.Dream_of_the_Blue_Veil;
import group.skills.list.level7.Plane_Shift;
import group.skills.list.level7.Teleport;
import group.skills.list.level8.Demiplane;
import group.skills.list.level8.Incendiary_Cloud;
import group.skills.list.level8.Maze;
import group.skills.list.level8.Mighty_Fortress;
import group.skills.list.level9.Blade_of_Disaster;
import group.skills.list.level9.Gate;
import group.skills.list.level9.Wish;

public class DetailsActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_details);
        String s = getIntent().getStringExtra("s");
        if(s.equals("1")){
            Acid_Splash as = new Acid_Splash();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("2")) {
            Create_Bonfire as = new Create_Bonfire();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("3")) {
            Infestation as = new Infestation();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("4")) {
            Mage_Hand as = new Mage_Hand();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("5")) {
            Fog_Cloud as = new Fog_Cloud();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("6")) {
            Grease as = new Grease();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("7")) {
            Healing_Elixir as = new Healing_Elixir();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("8")) {
            Ice_Knife as = new Ice_Knife();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("9")) {
            Air_Bubble as = new Air_Bubble();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("10")) {
            Cloud_of_Daggers as = new Cloud_of_Daggers();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("11")) {
            Dust_Devil as = new Dust_Devil();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("12")) {
            Flaming_Sphere as = new Flaming_Sphere();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("13")) {
            Conjure_Lesser_Demon as = new Conjure_Lesser_Demon();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("14")) {
            Sleet_Storm as = new Sleet_Storm();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("15")) {
            Stinking_Cloud as = new Stinking_Cloud();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("16")) {
            Thunder_Step as = new Thunder_Step();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("17")) {
            Conjure_Minor_Elementals as = new Conjure_Minor_Elementals();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("18")) {
            Dimension_Door as = new Dimension_Door();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("19")) {
            Evards_Black_Tentacles as = new Evards_Black_Tentacles();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("20")) {
            Galders_Speedy_Courier as = new Galders_Speedy_Courier();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("21")) {
            Conjure_Elemental as = new Conjure_Elemental();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("22")) {
            Infernal_Calling as = new Infernal_Calling();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("23")) {
            Steel_Wind_Strike as = new Steel_Wind_Strike();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("24")) {
            Teleportation_Circle as = new Teleportation_Circle();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("25")) {
            Arcane_Gate as = new Arcane_Gate();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("26")) {
            Scatter_Conjuration as = new Scatter_Conjuration();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("27")) {
            Dream_of_the_Blue_Veil as = new Dream_of_the_Blue_Veil();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("28")) {
            Plane_Shift as = new Plane_Shift();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("29")) {
            Teleport as = new Teleport();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("30")) {
            Demiplane as = new Demiplane();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("31")) {
            Incendiary_Cloud as = new Incendiary_Cloud();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("32")) {
            Maze as = new Maze();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("33")) {
            Mighty_Fortress as = new Mighty_Fortress();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("34")) {
            Blade_of_Disaster as = new Blade_of_Disaster();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("35")) {
            Gate as = new Gate();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        } else if (s.equals("36")) {
            Wish as = new Wish();
            TextView n = findViewById(R.id.name);
            TextView l = findViewById(R.id.level);
            TextView a = findViewById(R.id.action);
            TextView d = findViewById(R.id.distance);
            TextView ty = findViewById(R.id.type);
            TextView ti = findViewById(R.id.time);
            n.setText(as.getName());
            l.setText(as.getLevel());
            a.setText(as.getAction());
            d.setText(as.getDistance());
            ty.setText(as.getType());
            ti.setText(as.getTime());
        }
    }
}